[package]
name = 'unic0'
version = '0.1.0'
authors = ['Homa Wong <homawong@gmail.com>']
edition = '2018'

[dependencies]
clap = '3.0.0-beta.1'

[dev-dependencies]
assert_cmd = '^1'
predicates = '^1'
galvanic-assert = '^0'
