[package]
name = 'justc0'
version = '0.1.0'
authors = ['Homa Wong <homawong@gmail.com>']
edition = '2018'

[dependencies]

[dev-dependencies]
assert_cmd = '^1'
predicates = '^1'
galvanic-assert = '^0'
