[package]
authors = ["The Uni Project Developers"]
name = "unic_lexer"
version = "0.1.0"
license = "MIT"
edition = "2018"

repository = "https://github.com/uni-lng/uni/"
description = "Uni lexer used by unic"

[lib]
doctest = false
name = "unic_lexer"

[dependencies]
unicode-xid = "0.2.0"
