[package]
authors = ["The Rust Project Developers"]
name = "rustc_lexer"
version = "0.1.0"
license = "MIT"
edition = "2018"

repository = "https://github.com/uni-lng/uni/"
description = "Rust lexer used by rustc"

[lib]
doctest = false
name = "rustc_lexer"

[dependencies]
unicode-xid = "0.2.0"
