[package]
name = 'libunic_fs'
version = '0.1.0'
authors = ['Homa Wong <homawong@gmail.com>']
edition = '2018'

[dependencies]
anyhow = '1'
path-slash = '0'

[dependencies.libunic_compile_session]
path = '../libunic_compile_session'

[dev-dependencies]
